### ISSUE TITLE
UTF-8 characters can't be used

### ISSUE THREAD

**Issue by plavcik** [estrabd/vee#3]
if use czech characters like Jiří Navrátil

I'm getting

.vee/76657.1375955125.2013-08-08T11:45:25.raw:1: warning: can't find character with input code 196
.vee/76657.1375955125.2013-08-08T11:45:25.raw:7: warning: can't find character with input code 197
.vee/76657.1375955125.2013-08-08T11:45:25.raw:7: warning: can't find character with input code 195
.vee/76657.1375955125.2013-08-08T11:45:25.raw:7: warning: can't find character with input code 173
.vee/76657.1375955125.2013-08-08T11:45:25.raw:7: warning: can't find character with input code 161

and resulted html page looks

if use czech characters like Ji Navrtil

**Comment by Seestern** [comment]
Hello,

I am also German and noticed the missing "Umlaute" in the vee blog shell.
You can solve this problem if you modify the function "format_with_groff()" in this way:

 format_with_groff()
{ #sed 1liner from http://sed.sourceforge.net/sed1line.txt
  #----- Output: ASCII, without "preconv"
  #groff -man -Tascii "$RAW" >> bla.raw
  #----- Output: UTF-8, with "preconv"
  groff -k -man -Tutf8 "$RAW" >> bla.raw
  sed '/^$/N;/\n$/D' bla.raw >> "$FINAL"
  rm bla.raw
  #groff -man -Tascii "$RAW" >> "$FINAL"
}

This works for me. You find the function inside the bin/vee shell script.
See "man preconv" for more information.

This article on groff and UTF-8 was a good help:
http://lists.freebsd.org/pipermail/freebsd-questions/2011-July/232239.html

**Comment by estrabd** [comment]
Thanks. This looks like a FreeBSD-centric fix. I might have to do some checking for the OS like I do for sort.

**Comment by estrabd** [comment]
The working branch for this is "Issue-3-utf-groff".

**Comment by fhcflx** [comment]
Hi, 
My system is OS X 10.11.6 El Capitan.
I tried the solution suggested by @Seestern and got an error message:
```
groff: invalid option --k
```
Poking here and there I have found that groff comes pre-installed in Mac OS X, but its version is 1.19.2, and it has no support to the preconv function that is called by the ```groff -k``` option. So, I used homebrew to do a clean install of groff without messing with the system files in ```/usr/bin```:
```
brew install groff
```
And a ```which groff```call returned ```/usr/bin/local``` and its version was 1.22.3.
Tried again with the UTF-8 compatibility code and success! vee could use the right codification and my portuguese was up and running with all the special symbols!

**Comment by estrabd** [comment]
> Hi,
> My system is OS X 10.11.6 El Capitan.
> I tried the solution suggested by @Seestern and got an error message:
> 
> ```
> groff: invalid option --k
> ```
> 
> Poking here and there I have found that groff comes pre-installed in Mac OS X, but its version is 1.19.2, and it has no support to the preconv function that is called by the `groff -k` option. So, I used homebrew to do a clean install of groff without messing with the system files in `/usr/bin`:
> 
> ```
> brew install groff
> ```
> 
> And a `which groff`call returned `/usr/bin/local` and its version was 1.22.3.
> Tried again with the UTF-8 compatibility code and success! vee could use the right codification and my portuguese was up and running with all the special symbols!

Thank you for adding the follow up. Sorry! for the super late response, working on cleaning up this backlog.
