### ISSUE TITLE
Defining `DIR` as .vee does not work properly

### ISSUE THREAD

**Issue by matthiasbeyer** [estrabd/vee#33]
I have the following configuration (removed commented stuff):

```
INDEX=index.html
FOOTERTXT="hijacked by .veerc"
EDITOR=vim
FORMAT=html
INDEX=.vee/index.html
DIR=~/.vee
DRAFT=${DIR}/.vee.tmp.$$
PUBLISHED=`date "+%Y-%m-%d"`      # date formated for index page entry
```

But this failes. In vee#624 you are creating temporary files by piping:

``` bash
sort -t';' +0f -1 +1nr "$INDEX" > ".$INDEX.$$.sorted"
```

But if `$INDEX` is set to `.vee/index.html` (for not spamming my `~`, it wants to pipe to `..vee/index.html`. 

I assumed `$DIR` would be the directory where `vee` operates in, but apparently, it does also things outside of this directory. I would love to jail it in `~/.vee` for me, so it only creates files in there.

How to set this up properly? Maybe this is also a bugreport because of the mentioned line creating somehow buggy behaviour.

**Comment by estrabd** [comment]
IIRC, vee cd's to $DIR before doing anything, so $INDEX should be just a file name; the assumption is that that $INDEX is strictly a file located inside of $DIR.

Does that help?

**Comment by estrabd** [comment]
See comments in PR.

**Comment by estrabd** [comment]
>DIR=~/.vee
ah I see..
`vee` is meant to be run next to the .vee file
