### ISSUE TITLE
`vee -L` seems to be buggy

### ISSUE THREAD

**Issue by matthiasbeyer** [estrabd/vee#34]
I cannot edit the latest entry with

``` bash
vee -L 1
```

It opens `~/.vee/.raw`, which is then empty. It also prints:

``` bash
./dev/track/vee/bin/vee: line 397: sort -t. -nr: command not found
./dev/track/vee/bin/vee: line 397: sort -t. -nr: command not found
```

**Comment by Katsivelisp** [comment]
Yep, came to report this as well. Going to take a closer look though.

**Comment by estrabd** [comment]
Thanks, guys. Just saw this issue, weird. I'll take a look soon.

**Comment by estrabd** [comment]
Thanks for reporting, I'll take a look at this. Can you please post exact steps to reproduce this issue?

**Comment by estrabd** [comment]
@matthiasbeyer and @Katsivelisp - looking at old issues, I know it's been a while, but did you ever figure out the issue? What OS/environment is this on?

**Comment by matthiasbeyer** [comment]
Am not using this anymore, sorry. Feel free to close this.

**Comment by estrabd** [comment]
Thanks!
