### ISSUE TITLE
Do not generate full-patch links

### ISSUE THREAD

**Issue by matthiasbeyer** [estrabd/vee#39]
Currently, vee creates full-path links, which cannot be copied to a remove server for web-serving that easy.

I have to run:

``` bash
sed "s/\/home\/$USER\/\.vee/\./g" index.html > index.html
```

on my remote server to get a working version of the index file. This step shouldn't be required. Relative links to the directory of the index file should be created instead.

**Comment by estrabd** [comment]
vee is intended to be run on the webhost machine in ~/www or whatever.

**Comment by estrabd** [comment]
See comments in PR.

**Comment by estrabd** [comment]
cleaning up old issues, closing since OP deleted PR
